### ISSUE TITLE
project Roadmap

### ISSUE THREAD

**Issue by kalabiyau** [sensu/sensu-community-plugins#846]
This issue supposed to be central point of interactions about sensu-community plugins global goals

- [ ] packaging #847
- [ ] testing #848 
- [ ] documentation #866 
  - [ ] dev guidelines
  - [ ] documentaion
- [x] roadmap (this issue)
- [ ] Public Relations
  - [ ] Mission statement
  - [ ] website + dedicated community #867
  - [ ] Google Summer Of Code 2015 #865
